version: "3"
services:
  producer:
    image: python_producer
    build: ./producer
    container_name: producer
    volumes:
      - "./producer:/app"
    depends_on:
      - redis_pub_sub

  consumer:
    image: python_consumer
    build: ./consumer
    container_name: consumer
    volumes:
      - "./consumer:/app"
    depends_on:
      - redis_pub_sub
      - producer

  redis_pub_sub:
    image: redis
    container_name: redis_pub_sub
